### ISSUE TITLE
randomstuff[] variable only necessary due to indexing issue

### ISSUE THREAD

**Issue by jdw-creare** [brianc118/MPU9250#14]
[Here,](https://github.com/brianc118/MPU9250/blob/master/MPU9250.h#L252) you have an array that is unnecessary.  The memory issues you see are due to [this line](https://github.com/brianc118/MPU9250/blob/master/MPU9250.cpp#L422), which should be `mag_data_raw[i-7] = ...` instead of  `mag_data_raw[i] = ...`.  The write walks off the end of the `mag_data_raw` array and into the next section of memory, which in your case is the set of variables beginning at `my_clock`.

**Comment by brianc118** [comment]
Definitely an issue. Thanks!
