### ISSUE TITLE
add filtering

### ISSUE THREAD

**Issue by aster94** [brianc118/MPU9250#15]
hello Brian,

your lib is the first one where the magnetometer works. my congratulation
why don t you add a filtering?
examples:
https://github.com/kriswiner/MPU9250/blob/master/quaternionFilters.ino
or the improved sparkfun version:
https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library

i tried but it didin't work:
```
`#include <SPI.h>
#include <MPU9250.h>
#include "quaternion.h"
#include "Streaming.h"
#define SPI_CLOCK 8000000  // 8MHz clock works.
#define SS_PIN   10
unsigned long lastTime = 0;
float ax, ay, az, gx, gy, gz, mx, my, mz;
float Yaw, Pitch, Roll;


#define WAITFORINPUT(){            \
    while(!Serial.available()){};  \
    while(Serial.available()){    \
      Serial.read();               \
    };  Serial.flush();             \
  }

MPU9250 mpu(SPI_CLOCK, SS_PIN);

void setup() {
  Serial.begin(115200);
  SPI.begin();

  while (!Serial);
  Serial.println("Starting");

  mpu.init(true);

  uint8_t wai = mpu.whoami();
  Serial << "WAI:\t" << _HEX(wai) << newl;

  if (wai == 0x71 || wai == 0x73) {
    Serial.println("Successful connection to IMU");
  }
  else {
    Serial.println("Failed connection to IMU");
  }

  wai = mpu.AK8963_whoami();
  Serial << "WAI:\t" << _HEX(wai) << newl;

  if (wai == 0x48) {
    Serial.println("Successful connection to mag");
  }
  else {
    Serial.println("Failed connection to mag");
  }

  mpu.calib_acc();
  mpu.calib_mag();

  Serial.println("Send any char to begin main loop.");
  WAITFORINPUT();
}

void loop() {
  // various functions for reading
  // mpu.read_mag();
  // mpu.read_acc();
  // mpu.read_gyro();

  mpu.read_all();
  ax = mpu.accel_data[0];
  ay = mpu.accel_data[1];
  az = mpu.accel_data[1];

  gx = mpu.gyro_data[0];
  gy = mpu.gyro_data[1];
  gz = mpu.gyro_data[1];

  mx = mpu.mag_data[0];
  my = mpu.mag_data[1];
  mz = mpu.mag_data[2];


  Serial << "Gx:\t" << gx << "\tAx:\t" << ax << "\tMx:\t" << mx << newl;
  Serial << "Gy:\t" << gy << "\tAy:\t" << ay << "\tMy:\t" << my << newl;
  Serial << "Gz:\t" << gz << "\tAz:\t" << az << "\tMz:\t" << mz << newl;
  Serial << "T:\t" << mpu.temperature << newl << newl;

  MadgwickQuaternionUpdate(ax, ay, az, gx, gy, gz, mx, my, mz);
  yaw   = atan2(2.0f * (q[1] * q[2] + q[0] * q[3]), q[0] * q[0] + q[1] * q[1] - q[2] * q[2] - q[3] * q[3]);
  pitch = -asin(2.0f * (q[1] * q[3] - q[0] * q[2]));
  roll  = atan2(2.0f * (q[0] * q[1] + q[2] * q[3]), q[0] * q[0] - q[1] * q[1] - q[2] * q[2] + q[3] * q[3]);
  pitch *= 180.0f / PI;
  yaw   *= 180.0f / PI;
  yaw   -= 13.8; // Declination at Danville, California is 13 degrees 48 minutes and 47 seconds on 2014-04-04
  roll  *= 180.0f / PI;

  Serial << "Yaw, Pitch, Roll: " << newl;
  Serial << yaw << ", " << pitch << ", " << roll << newl;

  delay(50);
}`
```

quaternion.h
`float GyroMeasError = PI * (40.0f / 180.0f);   // gyroscope measurement error in rads/s (start at 40 deg/s)
float GyroMeasDrift = PI * (0.0f / 180.0f); // gyroscope measurement drift in rad/s/s (start at 0.0 deg/s/s)
float beta = sqrt(3.0f / 4.0f) * GyroMeasError;   // compute beta
float zeta = sqrt(3.0f / 4.0f) * GyroMeasDrift;   // compute zeta, the other free parameter in the Madgwick scheme usually set to a small or zero value
#define Kp 2.0f * 5.0f // these are the free parameters in the Mahony filter and fusion scheme, Kp for proportional feedback, Ki for integral
#define Ki 0.0f
uint32_t delt_t = 0; // used to control display output rate
uint32_t count = 0, sumCount = 0; // used to control display output rate
float pitch, yaw, roll;
float deltat = 0.0f, sum = 0.0f;        // integration interval for both filter schemes
uint32_t lastUpdate = 0, firstUpdate = 0; // used to calculate integration interval
uint32_t Now = 0;        // used to calculate integration interval
float q[4] = {1.0f, 0.0f, 0.0f, 0.0f};    // vector to hold quaternion
float eInt[3] = {0.0f, 0.0f, 0.0f};       // vector to hold integral error for Mahony method

void MadgwickQuaternionUpdate(float ax, float ay, float az, float gx, float gy, float gz, float mx, float my, float mz)
{
  float q1 = q[0], q2 = q[1], q3 = q[2], q4 = q[3];   // short name local variable for readability
  float norm;
  float hx, hy, _2bx, _2bz;
  float s1, s2, s3, s4;
  float qDot1, qDot2, qDot3, qDot4;

  // Auxiliary variables to avoid repeated arithmetic
  float _2q1mx;
  float _2q1my;
  float _2q1mz;
  float _2q2mx;
  float _4bx;
  float _4bz;
  float _2q1 = 2.0f * q1;
  float _2q2 = 2.0f * q2;
  float _2q3 = 2.0f * q3;
  float _2q4 = 2.0f * q4;
  float _2q1q3 = 2.0f * q1 * q3;
  float _2q3q4 = 2.0f * q3 * q4;
  float q1q1 = q1 * q1;
  float q1q2 = q1 * q2;
  float q1q3 = q1 * q3;
  float q1q4 = q1 * q4;
  float q2q2 = q2 * q2;
  float q2q3 = q2 * q3;
  float q2q4 = q2 * q4;
  float q3q3 = q3 * q3;
  float q3q4 = q3 * q4;
  float q4q4 = q4 * q4;

  // Normalise accelerometer measurement
  norm = sqrtf(ax * ax + ay * ay + az * az);
  if (norm == 0.0f) return; // handle NaN
  norm = 1.0f / norm;
  ax *= norm;
  ay *= norm;
  az *= norm;

  // Normalise magnetometer measurement
  norm = sqrtf(mx * mx + my * my + mz * mz);
  if (norm == 0.0f) return; // handle NaN
  norm = 1.0f / norm;
  mx *= norm;
  my *= norm;
  mz *= norm;

  // Reference direction of Earth's magnetic field
  _2q1mx = 2.0f * q1 * mx;
  _2q1my = 2.0f * q1 * my;
  _2q1mz = 2.0f * q1 * mz;
  _2q2mx = 2.0f * q2 * mx;
  hx = mx * q1q1 - _2q1my * q4 + _2q1mz * q3 + mx * q2q2 + _2q2 * my * q3 + _2q2 * mz * q4 - mx * q3q3 - mx * q4q4;
  hy = _2q1mx * q4 + my * q1q1 - _2q1mz * q2 + _2q2mx * q3 - my * q2q2 + my * q3q3 + _2q3 * mz * q4 - my * q4q4;
  _2bx = sqrtf(hx * hx + hy * hy);
  _2bz = -_2q1mx * q3 + _2q1my * q2 + mz * q1q1 + _2q2mx * q4 - mz * q2q2 + _2q3 * my * q4 - mz * q3q3 + mz * q4q4;
  _4bx = 2.0f * _2bx;
  _4bz = 2.0f * _2bz;

  // Gradient decent algorithm corrective step
  s1 = -_2q3 * (2.0f * q2q4 - _2q1q3 - ax) + _2q2 * (2.0f * q1q2 + _2q3q4 - ay) - _2bz * q3 * (_2bx * (0.5f - q3q3 - q4q4) + _2bz * (q2q4 - q1q3) - mx) + (-_2bx * q4 + _2bz * q2) * (_2bx * (q2q3 - q1q4) + _2bz * (q1q2 + q3q4) - my) + _2bx * q3 * (_2bx * (q1q3 + q2q4) + _2bz * (0.5f - q2q2 - q3q3) - mz);
  s2 = _2q4 * (2.0f * q2q4 - _2q1q3 - ax) + _2q1 * (2.0f * q1q2 + _2q3q4 - ay) - 4.0f * q2 * (1.0f - 2.0f * q2q2 - 2.0f * q3q3 - az) + _2bz * q4 * (_2bx * (0.5f - q3q3 - q4q4) + _2bz * (q2q4 - q1q3) - mx) + (_2bx * q3 + _2bz * q1) * (_2bx * (q2q3 - q1q4) + _2bz * (q1q2 + q3q4) - my) + (_2bx * q4 - _4bz * q2) * (_2bx * (q1q3 + q2q4) + _2bz * (0.5f - q2q2 - q3q3) - mz);
  s3 = -_2q1 * (2.0f * q2q4 - _2q1q3 - ax) + _2q4 * (2.0f * q1q2 + _2q3q4 - ay) - 4.0f * q3 * (1.0f - 2.0f * q2q2 - 2.0f * q3q3 - az) + (-_4bx * q3 - _2bz * q1) * (_2bx * (0.5f - q3q3 - q4q4) + _2bz * (q2q4 - q1q3) - mx) + (_2bx * q2 + _2bz * q4) * (_2bx * (q2q3 - q1q4) + _2bz * (q1q2 + q3q4) - my) + (_2bx * q1 - _4bz * q3) * (_2bx * (q1q3 + q2q4) + _2bz * (0.5f - q2q2 - q3q3) - mz);
  s4 = _2q2 * (2.0f * q2q4 - _2q1q3 - ax) + _2q3 * (2.0f * q1q2 + _2q3q4 - ay) + (-_4bx * q4 + _2bz * q2) * (_2bx * (0.5f - q3q3 - q4q4) + _2bz * (q2q4 - q1q3) - mx) + (-_2bx * q1 + _2bz * q3) * (_2bx * (q2q3 - q1q4) + _2bz * (q1q2 + q3q4) - my) + _2bx * q2 * (_2bx * (q1q3 + q2q4) + _2bz * (0.5f - q2q2 - q3q3) - mz);
  norm = sqrtf(s1 * s1 + s2 * s2 + s3 * s3 + s4 * s4);    // normalise step magnitude
  norm = 1.0f / norm;
  s1 *= norm;
  s2 *= norm;
  s3 *= norm;
  s4 *= norm;

  // Compute rate of change of quaternion
  qDot1 = 0.5f * (-q2 * gx - q3 * gy - q4 * gz) - beta * s1;
  qDot2 = 0.5f * (q1 * gx + q3 * gz - q4 * gy) - beta * s2;
  qDot3 = 0.5f * (q1 * gy - q2 * gz + q4 * gx) - beta * s3;
  qDot4 = 0.5f * (q1 * gz + q2 * gy - q3 * gx) - beta * s4;

  // Integrate to yield quaternion
  q1 += qDot1 * deltat;
  q2 += qDot2 * deltat;
  q3 += qDot3 * deltat;
  q4 += qDot4 * deltat;
  norm = sqrtf(q1 * q1 + q2 * q2 + q3 * q3 + q4 * q4);    // normalise quaternion
  norm = 1.0f / norm;
  q[0] = q1 * norm;
  q[1] = q2 * norm;
  q[2] = q3 * norm;
  q[3] = q4 * norm;

}`

**Comment by aster94** [comment]
ah anyway it seems that new mpu have different values of the who i am register, this is what my mpu9250 output
MPU: 0x73
MAG: 0xB6

**Comment by brianc118** [comment]
The point of the library is to give you the raw sensor outputs. You can easily just take an off the shelf filter and apply it without any difficulty. I think it'd only make sense to "add filtering" if we were using the DMP which does it for you ... but we aren't using the DMP.

Beware, quarternion/mahony filters are kind of a black box. If you don't strictly need them I recommend you just use something more simple like a complementary filter.

**Comment by brianc118** [comment]
Also the mag on the MPU-9250 really isn't that great. As a result, often it can mess up your filter results if you put too much weight on it.

**Comment by aster94** [comment]
Ok brian thank you anyway, i understand the point of your library
My need was to have yaw, pitch and roll but the math behind them is too difficult for me so i will need to use an already made library for them
