### ISSUE TITLE
Unstable Magnetometer Readings

### ISSUE THREAD

**Issue by xmlms** [brianc118/MPU9250#9]
Hi Brian,

Thank you for the library first of all, it really helps me to speed the things up. 

I'm planning to use the MPU-9250 to implement a tilt-compensated compass for my project. Prior to any calibration, I decided to run a quick test on my MPU-9250. Everything appeared to be fine, I can easily read valid data from both gyro and acce, which indicates my circuit connection is correct. However, the magnetometer's  (AK8963) readings looks like a mess. I just kept getting unstable results even I put the module on a flat surface and didn't move it. 

I calculated the headings of my device using just the readings from the magnetometer and the error went up to 5 degrees... That is really terrible, under the same test setup, my HMC5883L (calibrated) only gives me 0.8 degrees of error... 

`heading = atan2(mpu.mag_data[1], mpu.mag_data[0]) * 180 / PI ;`

I therefore compared the tri-axis readings between AK8963 and HMC5883L, it seems that the readings from AK8963 fluctuate more wildly than the one from HMC5883L. So I'm wondering if I've missed some critical steps or it is just the limitation of AK8963? And I would really appreciate if you can give me some hints on how I can make these measurements out of sense.

Cheers

**Comment by brianc118** [comment]
Yes the ak8369 is known to be worse than most other magnetometers.
